// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewShop struct {
	UserID      string  `json:"userId"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Country     *string `json:"country"`
	Region      *string `json:"region"`
	City        *string `json:"city"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Otp struct {
	SecretKey string `json:"secretKey"`
	ImgData   string `json:"imgData"`
}
