// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Otp struct {
	SecretKey string `json:"secretKey"`
	ImgData   string `json:"imgData"`
}
